CREATE TABLE GOODLIKE( -- 좋아요
	LIKE_NUM INT PRIMARY KEY, -- 번호 PK
	LIKE_BOARD_NUM INT, -- 좋아요 받은 글 FK
	LIKE_MEMBER_ID VARCHAR(50) NOT NULL -- 좋아요 누른 사람 FK
);

DROP TABLE GOODLIKE;
SELECT * FROM GOODLIKE;
SELECT * FROM GOODLIKE WHERE LIKE_BOARD_NUM=2;

-- FK 제약조건
ALTER TABLE GOODLIKE
ADD CONSTRAINT FK_LIKECONTENTS
FOREIGN KEY (LIKE_BOARD_NUM)
REFERENCES BOARD(BOARD_NUM)
ON DELETE CASCADE; -- 원본 데이터(글 삭제시) 데이터 삭제

-- 제약조건 삭제
ALTER TABLE GOODLIKE
DROP CONSTRAINT FK_LIKECONTENTS;

-- 제약조건 확인
SELECT constraint_name
FROM user_constraints
WHERE table_name = 'GOODLIKE' AND constraint_type = 'R';


ALTER TABLE GOODLIKE
ADD CONSTRAINT FK_LIKEMEMBER
FOREIGN KEY (LIKE_MEMBER_ID)
REFERENCES MEMBER(MEMBER_ID)
ON DELETE CASCADE; -- 원본 데이터(회원 탈퇴시) 데이터 삭제

-- 샘플 데이터
INSERT INTO GOODLIKE VALUES(1,2,'wlsrja3852@naver.com');
INSERT INTO GOODLIKE VALUES(2,2,'wlsrja3852@naver.com');
INSERT INTO GOODLIKE VALUES(3,5,'wlsrja3852@naver.com');
INSERT INTO GOODLIKE VALUES(4,2,'wlsrja3852@naver.com');
INSERT INTO GOODLIKE VALUES(5,4,'wlsrja3852@naver.com');
INSERT INTO GOODLIKE VALUES(6,2,'wlsrja3852@naver.com');